workflows:
  ios-project-debug: # Workflow ID
    name: iOS Debug # Workflow Name
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "MovieApp.xcodeproj" # Pastikan nama project benar
        XCODE_SCHEME: "MovieApp" # Pastikan scheme ini sudah shared
    working_directory: MovieApp # Hapus jika MovieApp.xcodeproj ada di root repo
    scripts:
      - name: Run tests
        working_directory: MovieApp
        script: |
          xcodebuild \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
          clean build test \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Build debug app
        working_directory: MovieApp
        script: |
          xcodebuild \
          build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    triggering:
        events:                       # List the events that trigger builds
            - push
        branch_patterns:
            - pattern: 'main'
                include: true
                source: true
        cancel_previous_builds: true


    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app

    publishing:
      email:
        recipients:
          - adji.firmansyah27@gmail.com # Email untuk notifikasi build status
        notify:
          success: true
          failure: true
